# Generated by Django 3.0.5 on 2021-03-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userPhotoURL',
            field=models.URLField(max_length=250),
        ),
    ]
