# Generated by Django 3.0.5 on 2021-03-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210320_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userPhotoURL',
            field=models.CharField(max_length=254, verbose_name='userPhotoURL'),
        ),
    ]
