# Generated by Django 3.0.5 on 2021-03-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210323_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userPhotoURL',
            field=models.CharField(max_length=254, verbose_name='userPhotoURL'),
        ),
    ]
