# Generated by Django 3.0.5 on 2021-03-23 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210323_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userPhotoURL',
        ),
    ]
