# Generated by Django 3.0.5 on 2021-03-24 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_userphotourl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.CharField(blank=True, choices=[('10-', '10-'), ('10-20', '10-20'), ('21-30', '21-30'), ('31-40', '31-40'), ('41-50', '41-50'), ('51-60', '51-60'), ('60+', '60+')], max_length=50, verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userPhotoURL',
            field=models.URLField(blank=True, max_length=254, verbose_name='userPhotoURL'),
        ),
    ]
